/* Generated by Together */

#ifndef ALMACEN_H
#define ALMACEN_H
#include "Certificado.h"
#include "ValidacionCertificado.h"
#include "FactoryPKI.h"
#include "AlmacenCAPI.h"
class Tarjeta;

class Almacen {
public:

    virtual Certificado* loadCertificado() =0;

    virtual void getValidacionCertificado() =0;

    bool close();

    bool open();

    protected :

    private :    
    int nombre;

    /** @link dependency */
    /*# ValidacionCertificado lnkRevocacion; */

    /** @link dependency 
     * @supplierRole Product
     * @clientRole Creator*/
    /*# Certificado lnkCertificado1; */
};
#endif //ALMACEN_H