/* Generated by Together */

#ifndef ALMACENCAPI_H
#define ALMACENCAPI_H
#include "Almacen.h"
#include "Tarjeta.h"
class Certificado;

/**
 * @stereotype toolkit 
 */
class AlmacenCAPI : public Almacen {


public:

    virtual Certificado* loadCertificado();

    void getRevocacion();

    private :    
    int handle;
};
#endif //ALMACENCAPI_H