/* Generated by Together */

#ifndef CERTCAPI_H
#define CERTCAPI_H
#include "Certificado.h"

/**
 * @stereotype toolkit 
 */
class CertCAPI : public Certificado {
public:

    protected :

    private :    
    int handle;
};
#endif //CERTCAPI_H