/* Generated by Together */

#ifndef CERTIFICADO_H
#define CERTIFICADO_H
#include "Firmador.h"
class Resumen;
class Firma;
class BufferDinamico;
class Almacen;

class Certificado {








    private :
    int fechaDesde;
    int fechaHasta;
    int emisor;
    int numSerie;
    int clavePublica;
    int asunto;
};
#endif //CERTIFICADO_H