/* Generated by Together */

#ifndef DOCUMENTO_H
#define DOCUMENTO_H
class FirmadorCAPI;

class Documento : public Firmable {



public:    

    virtual void readData();
};
#endif //DOCUMENTO_H