/* Generated by Together */

#include "FactoryCAPI.h"
void FactoryCAPI::createAlmacen(){
        // Write your code here
    }
Firmador * FactoryCAPI::createFirmador(){
        return new ConcreteProduct1();
    }
