/* Generated by Together */

#ifndef FACTORYCAPI_H
#define FACTORYCAPI_H
#include "FactoryPKI.h"
#include "AlmacenCAPI.h"
class Firmador;
class FactoryCAPI : public FactoryPKI {


public:

    virtual Firmador * createFirmador();

    virtual void createAlmacen();    
};
#endif //FACTORYCAPI_H