/* Generated by Together */

#ifndef FACTORYPKI_H
#define FACTORYPKI_H
#include "Firmador.h"
#include "FactoryCAPI.h"
#include "Almacen.h"
class FactoryPKI {
public:    

    virtual void createFirmador() =0;

    virtual void createAlmacen() =0;

    protected :

    private :

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @clientRole Factory
     * @supplierRole Product 
     */
    /*# Firmador _firmador; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @clientRole Factory
     * @supplierRole Product 
     */
    /*# Almacen _almacen; */
};
#endif //FACTORYPKI_H