/* Generated by Together */

#ifndef FIRMA_H
#define FIRMA_H

#include "Firmable.h"
#include "ISerializable.h"
#include "IPersistente.h"
#include "BufferDinamico.h"
#include "ConversorDatos.h"

class Firma : public ISerializable, public IPersistente , public BufferDinamico{
public:

    void setData(BYTE*, DWORD);

    virtual string serializar() =0;
    virtual bool deserializar(string) =0;

    virtual bool saveToFile(string,bool);
    virtual bool loadFromFile(string);
};
#endif //FIRMA_H