/* Generated by Together */

#ifndef FIRMADOR_H
#define FIRMADOR_H
#include "Firmable.h"
#include "BufferDinamico.h"
#include "Resumen.h"
#include "FactoryPKI.h"
class Tarjeta;
class Certificado;
class Firma;

class Firmador {
public:

    virtual Firma* firmar(Firmable&, Certificado & );

    bool validar(Firmable&, Firma&, Certificado&);

    virtual Resumen * resumir(BufferDinamico&);

private:    

    /** @link dependency */
    /*# Firmable lnkIFirmable; */

    /** @link dependency 
     * @clientRole Creator
     * @supplierRole Product*/
    /*# Firma lnkIFirma; */

    /** @link dependency */
    /*# BufferDinamico lnkBufferDinamico; */

    /** @link dependency 
     * @supplierRole Product
     * @clientRole Creator*/
    /*# Resumen lnkResumen; */
protected:
    virtual Firma* crearFirma(Certificado & p0);

    virtual Resumen * crearResumen();

    virtual bool calcularFirma(const BufferDinamico&, BufferDinamico&) =0;

    virtual bool calcularOriginal(const BufferDinamico& doc, Firma&, BufferDinamico &ori) =0;

    virtual bool calcularResumen(const BufferDinamico&, Resumen&) =0;

protected:

protected:




protected:

protected:
};
#endif //FIRMADOR_H