/* Generated by Together */

#ifndef FIRMAATTACHED_H
#define FIRMAATTACHED_H
#include "Firma.h"
class FirmaAttached : public Firma {


    protected :

    private :

public:    

    virtual string serializar();

    virtual bool deserializar(string);
};
#endif //FIRMAATTACHED_H