/* Generated by Together */

#include "Firmador.h"
bool Firmador::validar(Firmable&, Firma&, Certificado&){ }
Resumen * Firmador::resumir(BufferDinamico&){ }
class Resumen;

Resumen * Firmador::crearResumen()
{
    Resumen    ret;

    ret.
}
Firma* Firmador::crearFirma(Certificado & p0){}

void Firmador::operation1(){}

class Firma;

Firma* Firmador::firmar(Firmable&, Certificado & ){ }
