/* Generated by Together */

#include "FirmadorCAPI.h"

bool FirmadorCAPI::calcularResumen(const BufferDinamico&, BufferDinamico&){ }
bool FirmadorCAPI::calcularOriginal(BufferDinamico& doc, Firma&){ }
bool FirmadorCAPI::calcularFirma(const BufferDinamico&, BufferDinamico&){ }
