/* Generated by Together */

#ifndef FIRMABLE_H
#define FIRMABLE_H
#include "BufferDinamico.h"

class Firmable : public BufferDinamico {
public:

    virtual void readData() =0;
};
#endif //FIRMABLE_H