/* Generated by Together */

#ifndef FIRMAXML_H
#define FIRMAXML_H
#include "Firma.h"
class FirmaXML : public Firma {


    protected :

    private :

public:    

    virtual string serializar();

    virtual bool deserializar(string);
};
#endif //FIRMAXML_H