/* Generated by Together */

#ifndef FIRMADETACHED_H
#define FIRMADETACHED_H
#include "Firma.h"
#include "ConversorDatos.h"
class FirmaDetached : public Firma {


    protected :

    private :    

    /** @link dependency */
    /*# ConversorDatos lnkConversorDatos; */
public:    

    virtual string serializar();

    virtual bool deserializar(string);
};
#endif //FIRMADETACHED_H