/* Generated by Together */

#ifndef IPERSISTENTE_H
#define IPERSISTENTE_H

/** @interface */
class IPersistente {
public:    

    virtual bool saveToFile(string,bool) = 0;

    virtual bool loadFromFile(string) = 0;
};
#endif //IPERSISTENTE_H