/* Generated by Together */

#ifndef ISERIALIZABLE_H
#define ISERIALIZABLE_H

/** @interface */
class ISerializable {
public:    

    virtual string serializar() = 0;

    virtual bool deserializar(string) = 0;
};
#endif //ISERIALIZABLE_H