/* Generated by Together */

#ifndef OPERACION_H
#define OPERACION_H
class FirmadorCAPI;

class Operacion : public Firmable {



public:    

    virtual void readData();
};
#endif //OPERACION_H