/* Generated by Together */

#ifndef RESUMEN_H
#define RESUMEN_H
#include "BufferDinamico.h"

class Resumen : public BufferDinamico {
public:

    protected :

    private :

};
#endif //RESUMEN_H