/* Generated by Together */

#ifndef TARJETA_H
#define TARJETA_H
#include "Almacen.h"
#include "Firmador.h"
class AlmacenCAPI;

class Tarjeta {
public:    

    virtual bool conectar() =0;

    virtual bool desconectar() =0;

    virtual Almacen* abrirAlmacen(char * nombre p0) =0;

    virtual bool cerrarAlmacen(Almacen * * p0) =0;

    virtual Firmador* createFirmador(char * nombre p0) =0;

    protected :

        
private:    

    /** @link dependency 
     * @clientRole Creator
     * @supplierRole Product*/
    /*# Almacen lnkAlmacen; */

    /** @link dependency 
     * @clientRole Creator
     * @supplierRole Product*/
    /*# Firmador lnkFirmador; */
};
#endif //TARJETA_H