/* Generated by Together */

#include "TarjetaCAPI.h"
Firmador* TarjetaCAPI::getFirmador(char * nombre p0){ }
bool TarjetaCAPI::cerrarAlmacen(Almacen * * p0){ }
Almacen* TarjetaCAPI::abrirAlmacen(char * nombre p0){ }
