/* Generated by Together */

#ifndef TARJETACAPI_H
#define TARJETACAPI_H
#include "Tarjeta.h"
class Firmador;
class Almacen;

/**
 * @stereotype toolkit 
 */
class TarjetaCAPI : public Tarjeta {
public:    

    virtual Almacen* abrirAlmacen(char * nombre p0);

    virtual bool cerrarAlmacen(Almacen * * p0);

    virtual Firmador* getFirmador(char * nombre p0);

    protected :

    private :    
    int handle;
};
#endif //TARJETACAPI_H