/* Generated by Together */

#ifndef VALIDACIONCERTIFICADOLOCAL_H
#define VALIDACIONCERTIFICADOLOCAL_H
#include "ValidacionCertificado.h"
class Certificado;
class ValidacionCertificadoLocal : public ValidacionCertificado {
public:

    virtual void estaCaducado();

    protected :

    private :

};
#endif //VALIDACIONCERTIFICADOLOCAL_H