/* Generated by Together */

#ifndef VALIDACIONCERTIFICADOONLINE_H
#define VALIDACIONCERTIFICADOONLINE_H
#include "ValidacionCertificado.h"
class Certificado;
class ValidacionCertificadoOnline : public ValidacionCertificado {
public:    

    virtual void estaRevocado(Certificado&);

    void estaCaducado();

    protected :

    private :

};
#endif //VALIDACIONCERTIFICADOONLINE_H