/* Generated by Together */

#ifndef VALIDACIONCERTIFICADOCAPI_H
#define VALIDACIONCERTIFICADOCAPI_H
#include "ValidacionCertificadoLocal.h"
#include "AlmacenCAPI.h"
class Certificado;
class ValidacionCertificadoCAPI : public ValidacionCertificadoLocal {
public:    

    virtual void estaRevocado(Certificado&);

    virtual void estaCaducado();

    protected :

    private :    

    /** @link dependency */
    /*# AlmacenCAPI lnkAlmacenCAPI; */
};
#endif //VALIDACIONCERTIFICADOCAPI_H